### ISSUE TITLE
want a example

### ISSUE THREAD

**Issue by lrc0** [JoshuaDoes/adpcm-go#2]
why decode the adpcm []byte data get a []int data. 
whether need to trans []int data into []byte data again.
can you give a example to explain how to use the decoded data

**Comment by JoshuaDoes** [comment]
> 
> 
> why decode the adpcm []byte data get a []int data.
> whether need to trans []int data into []byte data again.
> can you give a example to explain how to use the decoded data

ADPCM is essentially reversed PCM audio data. If you don't understand how to use PCM audio, you shouldn't be using this library to begin with. But once you do understand how it works, take the []int of PCM samples and throw it into a WAV encoder.

**Comment by yupeng2015** [comment]
> why decode the adpcm []byte data get a []int data. whether need to trans []int data into []byte data again. can you give a example to explain how to use the decoded data

I have this problem too, have you solved it?
